#!/usr/bin/php
<?php declare(strict_types=1);

/**
 *
 * @author    <contact@lotfio.net>
 * @package   Conso PHP Console Creator
 * @version   0.1.0
 * @license   MIT
 * @category  CLI
 * @copyright 2019 Lotfio Lakehal
 */

require 'vendor/autoload.php';

use Conso\Input;
use Conso\Output;
use Conso\Config;

/**
 * load config
 */
Config::load();

/**
 * adding custom config
 * example:
 * COMMANDS  => your commands dir
 * NAMESPACE => your commands namespace
 */
//Config::add('config.php');
/**
 * get instance
 */
$app = new Conso\App(new Input, new Output);


// start application
$app->run();