#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 *
 * @author    <contact@lotfio.net>
 * @package   Conso PHP Console Creator
 * @version   0.1.0
 * @license   MIT
 * @category  CLI
 * @copyright 2019 Lotfio Lakehal
 */

require 'vendor/autoload.php';

use Conso\Input;
use Conso\Output;
use OoFile\Conf;

/**
 * adding custom config
 *
 */
Conf::add(__DIR__.'/src/Conso/conf'); // load config

/**
 * get instance
 */
$app = new Conso\App(new Input, new Output);


// start application
$app->run();