#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 *
 * @author    <contact@lotfio.net>
 * @package   Conso PHP Console Creator
 * @version   0.1.0
 * @license   MIT
 * @category  CLI
 * @copyright 2019 Lotfio Lakehal
 */

require 'vendor/autoload.php';

use Conso\Input;
use Conso\Output;
use Conso\Config;

/**
 * adding custom config
 *
 */
Config::load(); // load config
Config::appName();
Config::appVersion();
Config::appRelease();
Config::appLogo();
Config::appDefaultCommand();

//Config::addCommands(__DIR__ . DIRECTORY_SEPARATOR .'Console'); your commands file should be added here
//Config::addNamespace('Console\\'); // your commands namespace shoud be added here
/**
 * get instance
 */
$app = new Conso\App(new Input, new Output);


// start application
$app->run();